services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  weather-api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - POSTGRES_PASSWORD=${DB_USERNAME}
      - POSTGRES_USER=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME} 
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - WEATHER_API_URL=${WEATHER_API_URL}
      - JWT_SECRET=${JWT_SECRET}

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: